{% set version = "3.5.5" %}

package:
  name: calceph
  version: {{ version }}

source:
  url: https://www.imcce.fr/content/medias/recherche/equipes/asd/calceph/calceph-{{ version }}.tar.gz
  sha256: 34b7a4fbcbfff3bd54de8f4636fdbb8a8345c7432fbbe3a61a4f5d90b76bb962
  patches:
    - win_build_fix.diff

build:
  number: 0
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('calceph', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make                # [unix]

test:
  commands:
    - test -f $PREFIX/include/calceph.h                           # [unix]
    - test -f $PREFIX/lib/libcalceph${SHLIB_EXT}                  # [unix]
    - if not exist %PREFIX%\\Library\\include\\calceph.h exit 1   # [win]
    - if not exist %PREFIX%\\Library\\lib\\libcalceph.lib exit 1  # [win]

about:
  home: https://www.imcce.fr/inpop/calceph/
  license: CECILL-C OR CECILL-B OR CECILL-2.1
  license_file: COPYING_CECILL_C.LIB
  summary: A library to access the binary planetary ephemeris files, such INPOPxx, JPL DExxx and SPICE ephemeris files.

extra:
  recipe-maintainers:
    - bluescarni
